/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Facility, FacilityType } from "./types";

export const INITIAL_FACILITIES: Facility[] = [
  // --- ENTRANCES (4) ---
  {
    id: "gate-a",
    name: "Gate A (North Entrance)",
    type: FacilityType.ENTRANCE,
    description: "Main north entrance with express security lines. Wheelchair accessible.",
    capacity: 10000,
    crowdLevel: "Medium",
    crowdPercent: 55,
    isOpen: true,
    waitTime: 8,
    x: 50,
    y: 5,
    level: 1,
    block: "Block A"
  },
  {
    id: "gate-b",
    name: "Gate B (Northeast Entrance)",
    type: FacilityType.ENTRANCE,
    description: "Northeast entrance. Close to Metro transit link.",
    capacity: 8000,
    crowdLevel: "High",
    crowdPercent: 85,
    isOpen: true,
    waitTime: 22,
    x: 82,
    y: 18,
    level: 1,
    block: "Block B"
  },
  {
    id: "gate-c",
    name: "Gate C (East Entrance)",
    type: FacilityType.ENTRANCE,
    description: "East gate with multi-lane ticket scanners.",
    capacity: 8000,
    crowdLevel: "Low",
    crowdPercent: 20,
    isOpen: true,
    waitTime: 2,
    x: 95,
    y: 50,
    level: 1,
    block: "Block D"
  },
  {
    id: "gate-e",
    name: "Gate E (South Entrance)",
    type: FacilityType.ENTRANCE,
    description: "Main south entrance. Directly linked to taxi stand.",
    capacity: 10000,
    crowdLevel: "Critical",
    crowdPercent: 95,
    isOpen: true,
    waitTime: 35,
    x: 50,
    y: 95,
    level: 1,
    block: "Block G"
  },

  // --- EXITS (3) ---
  {
    id: "exit-1",
    name: "Exit 1 (Northwest Perimeter)",
    type: FacilityType.EXIT,
    description: "Primary fast-flow exit point towards parkway fields.",
    capacity: 15000,
    crowdLevel: "Low",
    crowdPercent: 10,
    isOpen: true,
    waitTime: 0,
    x: 10,
    y: 15,
    level: 1,
    block: "Block L"
  },
  {
    id: "exit-2",
    name: "Exit 2 (Southeast Perimeter)",
    type: FacilityType.EXIT,
    description: "East pedestrian dispersal gate toward subway.",
    capacity: 12000,
    crowdLevel: "Medium",
    crowdPercent: 45,
    isOpen: true,
    waitTime: 3,
    x: 90,
    y: 85,
    level: 1,
    block: "Block F"
  },
  {
    id: "exit-3",
    name: "Exit 3 (Southwest Perimeter)",
    type: FacilityType.EXIT,
    description: "West pedestrian dispersal gate toward parking zone B.",
    capacity: 12000,
    crowdLevel: "Low",
    crowdPercent: 15,
    isOpen: true,
    waitTime: 0,
    x: 10,
    y: 85,
    level: 1,
    block: "Block I"
  },

  // --- SEATING BLOCKS (5) ---
  {
    id: "seat-block-101",
    name: "Seating Block 101 (North Lower)",
    type: FacilityType.SEAT,
    description: "Vibrant lower terrace behind the northern goal post.",
    capacity: 2500,
    crowdLevel: "High",
    crowdPercent: 88,
    isOpen: true,
    waitTime: 0,
    x: 50,
    y: 20,
    level: 1,
    block: "Block A"
  },
  {
    id: "seat-block-104",
    name: "Seating Block 104 (East Lower)",
    type: FacilityType.SEAT,
    description: "Prime eastern sideline lower seating with stellar field views.",
    capacity: 3500,
    crowdLevel: "High",
    crowdPercent: 92,
    isOpen: true,
    waitTime: 0,
    x: 80,
    y: 50,
    level: 1,
    block: "Block D"
  },
  {
    id: "seat-block-107",
    name: "Seating Block 107 (South Lower)",
    type: FacilityType.SEAT,
    description: "Vibrant lower terrace behind the southern goal post.",
    capacity: 2500,
    crowdLevel: "Critical",
    crowdPercent: 96,
    isOpen: true,
    waitTime: 0,
    x: 50,
    y: 80,
    level: 1,
    block: "Block G"
  },
  {
    id: "seat-block-110",
    name: "Seating Block 110 (West Lower)",
    type: FacilityType.SEAT,
    description: "Western sideline lower seating, adjacent to team benches.",
    capacity: 3500,
    crowdLevel: "Medium",
    crowdPercent: 70,
    isOpen: true,
    waitTime: 0,
    x: 20,
    y: 50,
    level: 1,
    block: "Block J"
  },
  {
    id: "seat-block-205",
    name: "Seating Block 205 (East Upper)",
    type: FacilityType.SEAT,
    description: "Upper tier panoramic sideline view. Accessible by escalator East.",
    capacity: 4000,
    crowdLevel: "Medium",
    crowdPercent: 60,
    isOpen: true,
    waitTime: 0,
    x: 85,
    y: 50,
    level: 2,
    block: "Block E"
  },

  // --- WASHROOMS (3) ---
  {
    id: "washroom-n1",
    name: "Concourse Washroom North (M/F)",
    type: FacilityType.WASHROOM,
    description: "Standard public male & female restrooms. Equipped with water-saving fixtures.",
    capacity: 50,
    crowdLevel: "Medium",
    crowdPercent: 50,
    isOpen: true,
    waitTime: 4,
    x: 35,
    y: 12,
    level: 1,
    block: "Block B"
  },
  {
    id: "washroom-e1",
    name: "Concourse Washroom East (M/F)",
    type: FacilityType.WASHROOM,
    description: "High-capacity east wing public restrooms.",
    capacity: 60,
    crowdLevel: "High",
    crowdPercent: 75,
    isOpen: true,
    waitTime: 7,
    x: 88,
    y: 38,
    level: 1,
    block: "Block C"
  },
  {
    id: "washroom-s1",
    name: "Concourse Washroom South (M/F)",
    type: FacilityType.WASHROOM,
    description: "Public restrooms adjacent to the South Food Court.",
    capacity: 50,
    crowdLevel: "Critical",
    crowdPercent: 95,
    isOpen: true,
    waitTime: 12,
    x: 35,
    y: 88,
    level: 1,
    block: "Block H"
  },

  // --- ACCESSIBLE WASHROOMS (2) ---
  {
    id: "acc-washroom-n",
    name: "Accessible Washroom North",
    type: FacilityType.ACCESSIBLE_WASHROOM,
    description: "Wheelchair accessible private unisex restroom with safety grab rails and distress alarm.",
    capacity: 5,
    crowdLevel: "Low",
    crowdPercent: 20,
    isOpen: true,
    waitTime: 1,
    x: 38,
    y: 12,
    level: 1,
    block: "Block B"
  },
  {
    id: "acc-washroom-s",
    name: "Accessible Washroom South",
    type: FacilityType.ACCESSIBLE_WASHROOM,
    description: "Wheelchair accessible unisex restroom located near Elevator South.",
    capacity: 5,
    crowdLevel: "Medium",
    crowdPercent: 40,
    isOpen: true,
    waitTime: 3,
    x: 38,
    y: 88,
    level: 1,
    block: "Block H"
  },

  // --- FOOD COURTS (2) ---
  {
    id: "foodcourt-north",
    name: "Grand Pavilion Food Court",
    type: FacilityType.FOOD_COURT,
    description: "Spacious dining area featuring a wide variety of global cuisines and premium seating.",
    capacity: 400,
    crowdLevel: "Medium",
    crowdPercent: 65,
    isOpen: true,
    waitTime: 10,
    x: 65,
    y: 12,
    level: 1,
    block: "Block A"
  },
  {
    id: "foodcourt-south",
    name: "South Plaza Food Concourse",
    type: FacilityType.FOOD_COURT,
    description: "Lively central food court serving multi-national sports fans.",
    capacity: 450,
    crowdLevel: "Critical",
    crowdPercent: 92,
    isOpen: true,
    waitTime: 18,
    x: 65,
    y: 88,
    level: 1,
    block: "Block G"
  },

  // --- FOOD STALLS (3) ---
  {
    id: "foodstall-tacos",
    name: "Tacos El Campéon (Stall 1)",
    type: FacilityType.FOOD_STALL,
    description: "Voted fan-favorite for premium carne asada and birria soccer tacos.",
    capacity: 80,
    crowdLevel: "High",
    crowdPercent: 80,
    isOpen: true,
    waitTime: 8,
    x: 60,
    y: 14,
    level: 1,
    block: "Block A"
  },
  {
    id: "foodstall-burgers",
    name: "Burger Goal (Stall 2)",
    type: FacilityType.FOOD_STALL,
    description: "Classic flame-grilled gourmet smash burgers and golden football fries.",
    capacity: 90,
    crowdLevel: "Medium",
    crowdPercent: 55,
    isOpen: true,
    waitTime: 5,
    x: 68,
    y: 14,
    level: 1,
    block: "Block B"
  },
  {
    id: "foodstall-pizza",
    name: "Pizza Goal (Stall 3)",
    type: FacilityType.FOOD_STALL,
    description: "Wood-fired artisanal personal pizzas. Express slices available.",
    capacity: 85,
    crowdLevel: "High",
    crowdPercent: 85,
    isOpen: true,
    waitTime: 9,
    x: 60,
    y: 86,
    level: 1,
    block: "Block G"
  },

  // --- BEVERAGE STALLS (3) ---
  {
    id: "bevstall-corner",
    name: "Corner Kick Hydration",
    type: FacilityType.BEVERAGE_STALL,
    description: "Premium ice cold beers, craft sodas, and sports energy drinks.",
    capacity: 120,
    crowdLevel: "Medium",
    crowdPercent: 60,
    isOpen: true,
    waitTime: 3,
    x: 25,
    y: 35,
    level: 1,
    block: "Block K"
  },
  {
    id: "bevstall-penalty",
    name: "Penalty Kick Brews",
    type: FacilityType.BEVERAGE_STALL,
    description: "Fast-serving beer taps, draft coolers, and refreshing mocktails.",
    capacity: 120,
    crowdLevel: "High",
    crowdPercent: 78,
    isOpen: true,
    waitTime: 6,
    x: 75,
    y: 35,
    level: 1,
    block: "Block C"
  },
  {
    id: "bevstall-west",
    name: "West Wing Beverage Lounge",
    type: FacilityType.BEVERAGE_STALL,
    description: "Draft beer stand and gourmet iced coffee selection.",
    capacity: 100,
    crowdLevel: "Low",
    crowdPercent: 30,
    isOpen: true,
    waitTime: 1,
    x: 25,
    y: 65,
    level: 1,
    block: "Block I"
  },

  // --- MEDICAL CENTERS (2) ---
  {
    id: "medical-east",
    name: "Medical Clinic East (Main)",
    type: FacilityType.MEDICAL,
    description: "Main medical emergency center. Fully staffed with emergency doctors and ambulance access.",
    capacity: 50,
    crowdLevel: "Low",
    crowdPercent: 15,
    isOpen: true,
    waitTime: 0,
    x: 88,
    y: 42,
    level: 1,
    block: "Block D"
  },
  {
    id: "firstaid-north",
    name: "First Aid Post North Wing",
    type: FacilityType.FIRST_AID,
    description: "Fast-response first aid satellite room. Staffed by certified Red Cross volunteers.",
    capacity: 10,
    crowdLevel: "Low",
    crowdPercent: 20,
    isOpen: true,
    waitTime: 1,
    x: 20,
    y: 12,
    level: 1,
    block: "Block L"
  },

  // --- INFORMATION DESKS (2) ---
  {
    id: "info-desk-north",
    name: "Information Desk North",
    type: FacilityType.INFO,
    description: "Central visitor info desk. Multilingual volunteers present. High-contrast stadium map prints.",
    capacity: 30,
    crowdLevel: "Medium",
    crowdPercent: 45,
    isOpen: true,
    waitTime: 3,
    x: 45,
    y: 10,
    level: 1,
    block: "Block A"
  },
  {
    id: "info-desk-south",
    name: "Information Desk South",
    type: FacilityType.INFO,
    description: "Visitor and transit assistance kiosk near South Plaza.",
    capacity: 30,
    crowdLevel: "High",
    crowdPercent: 80,
    isOpen: true,
    waitTime: 8,
    x: 45,
    y: 90,
    level: 1,
    block: "Block G"
  },

  // --- LOST AND FOUND (1) ---
  {
    id: "lost-found-central",
    name: "Central Lost & Found Office",
    type: FacilityType.LOST_FOUND,
    description: "Official repository for lost items. Connected to AI digital ticket catalog system.",
    capacity: 25,
    crowdLevel: "Low",
    crowdPercent: 30,
    isOpen: true,
    waitTime: 2,
    x: 12,
    y: 50,
    level: 1,
    block: "Block K"
  },

  // --- PARKING (2) ---
  {
    id: "parking-p1",
    name: "Parking Area P1 (VIP & Accessible)",
    type: FacilityType.PARKING,
    description: "Closest parking deck. Highly secured. Features 120 reserved accessible blue-sticker slots.",
    capacity: 500,
    crowdLevel: "Medium",
    crowdPercent: 55,
    isOpen: true,
    waitTime: 0,
    x: 10,
    y: 5,
    level: 1,
    block: "Block L"
  },
  {
    id: "parking-p2",
    name: "Parking Area P2 (General Lot)",
    type: FacilityType.PARKING,
    description: "Multi-level general park & walk parking lot.",
    capacity: 3000,
    crowdLevel: "High",
    crowdPercent: 90,
    isOpen: true,
    waitTime: 15,
    x: 90,
    y: 95,
    level: 1,
    block: "Block F"
  },

  // --- TAXI PICKUPS (1) ---
  {
    id: "taxi-pickup",
    name: "Taxi Pickup & Drop-off Stand",
    type: FacilityType.TAXI,
    description: "Convenient taxi rank located directly outside the South Entrance.",
    capacity: 150,
    crowdLevel: "Critical",
    crowdPercent: 98,
    isOpen: true,
    waitTime: 20,
    x: 35,
    y: 95,
    level: 1,
    block: "Block H"
  },

  // --- BUS PICKUPS (1) ---
  {
    id: "bus-pickup",
    name: "FIFA Shuttle Bus Transit Hub",
    type: FacilityType.BUS,
    description: "Direct rapid shuttles linking fans to FIFA fan zones and city metro terminals.",
    capacity: 500,
    crowdLevel: "High",
    crowdPercent: 80,
    isOpen: true,
    waitTime: 10,
    x: 65,
    y: 95,
    level: 1,
    block: "Block F"
  },

  // --- ELEVATORS (2) ---
  {
    id: "elevator-north",
    name: "Elevator North (Suites & VIP)",
    type: FacilityType.ELEVATOR,
    description: "Accessible vertical lift to Level 2 Presidential Suites & VIP Lounges.",
    capacity: 15,
    crowdLevel: "Medium",
    crowdPercent: 50,
    isOpen: true,
    waitTime: 2,
    x: 57,
    y: 15,
    level: 1,
    block: "Block A"
  },
  {
    id: "elevator-south",
    name: "Elevator South (Priority Wheelchair)",
    type: FacilityType.ELEVATOR,
    description: "Priority elevator strictly reserved for wheelchair users and strollers.",
    capacity: 15,
    crowdLevel: "High",
    crowdPercent: 80,
    isOpen: true,
    waitTime: 4,
    x: 57,
    y: 85,
    level: 1,
    block: "Block G"
  },

  // --- ESCALATORS (2) ---
  {
    id: "escalator-east",
    name: "Escalator East Wing",
    type: FacilityType.ESCALATOR,
    description: "Double-capacity moving staircase leading to Level 2 concourse and restaurants.",
    capacity: 120,
    crowdLevel: "Medium",
    crowdPercent: 60,
    isOpen: true,
    waitTime: 0,
    x: 85,
    y: 55,
    level: 1,
    block: "Block C"
  },
  {
    id: "escalator-west",
    name: "Escalator West Wing",
    type: FacilityType.ESCALATOR,
    description: "Moving staircase leading to western luxury suites.",
    capacity: 120,
    crowdLevel: "Low",
    crowdPercent: 30,
    isOpen: true,
    waitTime: 0,
    x: 15,
    y: 45,
    level: 1,
    block: "Block J"
  },

  // --- WHEELCHAIR ROUTES (2) ---
  {
    id: "wheelchair-ramp-west",
    name: "Wheelchair Priority Route West",
    type: FacilityType.WHEELCHAIR_ROUTE,
    description: "Low-gradient priority ramp for seamless wheelchair mobility into Tier-1 Seating Block 110.",
    capacity: 100,
    crowdLevel: "Low",
    crowdPercent: 10,
    isOpen: true,
    waitTime: 0,
    x: 10,
    y: 45,
    level: 1,
    block: "Block J"
  },
  {
    id: "wheelchair-ramp-north",
    name: "Wheelchair Priority Route North",
    type: FacilityType.WHEELCHAIR_ROUTE,
    description: "Safe, ADA-compliant wheelchair pathway connecting Gate A directly to the North Concourse.",
    capacity: 100,
    crowdLevel: "Low",
    crowdPercent: 12,
    isOpen: true,
    waitTime: 0,
    x: 43,
    y: 8,
    level: 1,
    block: "Block A"
  },

  // --- MERCHANDISE STORES (2) ---
  {
    id: "merch-megastore",
    name: "Official FIFA Mega Store",
    type: FacilityType.MERCHANDISE,
    description: "The primary tournament superstore featuring official match balls, jerseys, and customizable gear.",
    capacity: 350,
    crowdLevel: "Critical",
    crowdPercent: 95,
    isOpen: true,
    waitTime: 15,
    x: 50,
    y: 40,
    level: 1,
    block: "Block K"
  },
  {
    id: "merch-express",
    name: "Fan Shop Express (West)",
    type: FacilityType.MERCHANDISE,
    description: "Quick-stop kiosk offering tournament flags, caps, scarves, and collectable matchday badges.",
    capacity: 40,
    crowdLevel: "Medium",
    crowdPercent: 50,
    isOpen: true,
    waitTime: 3,
    x: 14,
    y: 35,
    level: 1,
    block: "Block K"
  },

  // --- PRAYER ROOMS (1) ---
  {
    id: "prayer-multifaith",
    name: "Multifaith Prayer Room",
    type: FacilityType.PRAYER,
    description: "A tranquil, sound-insulated prayer and meditation space. Complete with ablution facilities.",
    capacity: 40,
    crowdLevel: "Low",
    crowdPercent: 25,
    isOpen: true,
    waitTime: 0,
    x: 14,
    y: 65,
    level: 1,
    block: "Block I"
  },

  // --- BABY CARE ROOMS (1) ---
  {
    id: "babycare-north",
    name: "Baby Care Room (North Wing)",
    type: FacilityType.BABY_CARE,
    description: "Private quiet nursery room with diaper changing stations, private feeding pods, and hot water access.",
    capacity: 15,
    crowdLevel: "Low",
    crowdPercent: 15,
    isOpen: true,
    waitTime: 0,
    x: 22,
    y: 14,
    level: 1,
    block: "Block L"
  },

  // --- CHARGING STATIONS (2) ---
  {
    id: "charging-hub-east",
    name: "Fast Charging Hub (East Gate)",
    type: FacilityType.CHARGING,
    description: "Equipped with high-speed multi-cable outputs and secure lockers to safely charge your smart devices.",
    capacity: 50,
    crowdLevel: "Medium",
    crowdPercent: 65,
    isOpen: true,
    waitTime: 1,
    x: 85,
    y: 45,
    level: 1,
    block: "Block D"
  },
  {
    id: "charging-hub-south",
    name: "Solar Charging Hub (South Gate)",
    type: FacilityType.CHARGING,
    description: "Environmentally friendly, solar-powered multi-device charging stand near South Food Court.",
    capacity: 30,
    crowdLevel: "High",
    crowdPercent: 80,
    isOpen: true,
    waitTime: 3,
    x: 48,
    y: 92,
    level: 1,
    block: "Block G"
  },

  // --- EMERGENCY EXITS (2) ---
  {
    id: "em-exit-north",
    name: "Emergency Exit (North Gate A)",
    type: FacilityType.EMERGENCY_EXIT,
    description: "Fast-dispersal safety exit pathway. Monitored strictly by stadium security. Push bars active.",
    capacity: 20000,
    crowdLevel: "Low",
    crowdPercent: 0,
    isOpen: true,
    waitTime: 0,
    x: 53,
    y: 3,
    level: 1,
    block: "Block A"
  },
  {
    id: "em-exit-south",
    name: "Emergency Exit (South Gate E)",
    type: FacilityType.EMERGENCY_EXIT,
    description: "Fast-dispersal safety exit pathway toward transit drop off points. Automatically triggers.",
    capacity: 20000,
    crowdLevel: "Low",
    crowdPercent: 0,
    isOpen: true,
    waitTime: 0,
    x: 53,
    y: 97,
    level: 1,
    block: "Block G"
  },

  // --- VIP LOUNGES (2) ---
  {
    id: "vip-presidential",
    name: "The Presidential VIP Suite",
    type: FacilityType.VIP,
    description: "Exclusive Level 2 climate-controlled suite hosting distinguished state officials and FIFA delegates.",
    capacity: 100,
    crowdLevel: "Low",
    crowdPercent: 40,
    isOpen: true,
    waitTime: 0,
    x: 50,
    y: 48,
    level: 2,
    block: "Block E"
  },
  {
    id: "vip-platinum",
    name: "Platinum Club Hospitality Lounge",
    type: FacilityType.VIP,
    description: "Luxury club hospitality with premium buffets, direct balcony stadium seats, and concierge.",
    capacity: 300,
    crowdLevel: "Medium",
    crowdPercent: 55,
    isOpen: true,
    waitTime: 0,
    x: 50,
    y: 52,
    level: 2,
    block: "Block E"
  }
];
